# Generated by Django 2.2.4 on 2019-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='articlePic_l',
        ),
        migrations.AddField(
            model_name='blog',
            name='articlePic_s',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='gridPic_l',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='gridPic_s',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
