# Generated by Django 2.2.4 on 2019-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190927_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture_caption',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
