# Generated by Django 2.2.4 on 2019-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_picture_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='conclusion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
